# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=50, null=True, verbose_name='State')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('visit_datetime', models.DateTimeField(auto_now=True, verbose_name='Login Date Time')),
                ('browser', models.CharField(max_length=30, null=True, verbose_name='Browser')),
                ('browser_version', models.CharField(max_length=20, null=True, verbose_name='Browser Version')),
                ('ipaddress', models.CharField(max_length=20, null=True, verbose_name='IP Address')),
                ('os_info', models.CharField(max_length=30, null=True, verbose_name='OS Information')),
                ('os_info_version', models.CharField(max_length=20, null=True, verbose_name='OS Version')),
                ('device_type', models.CharField(max_length=20, null=True, verbose_name='Device Type')),
                ('device_name', models.CharField(max_length=20, null=True, verbose_name='Device Name')),
                ('device_name_brand', models.CharField(max_length=20, null=True, verbose_name='Device Brand Name')),
                ('device_name_model', models.CharField(max_length=20, null=True, verbose_name='Device Model Name')),
                ('unique_computer_processor', models.CharField(max_length=255, null=True, verbose_name='Computer Processor')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'visitors',
                'ordering': ['visit_datetime'],
                'verbose_name': 'visitor',
            },
        ),
    ]
