# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0003_auto_20170324_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='unique_computer_processor',
        ),
        migrations.AddField(
            model_name='visitor',
            name='http_referer',
            field=models.URLField(blank=True, null=True, verbose_name='HTTP_REFERER URL'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='request_url',
            field=models.URLField(null=True, verbose_name='Request URL'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
